pipeline {
  agent any
  environment {
		DEPLOY_CREDS = credentials('deploy-anypoint-user')
	    MULE_VERSION = "4.4.0"
	    BG = "Cap4"
	    BGID = "6a860bc2-7c16-4fc4-8c42-9a362133e5f9"
	    WORKERS = "1"
	    WORKERSIZE = "Micro"
		APP_NAME = "customer-api"
		REGION= "us-east-2"
  } 
  triggers {
        pollSCM('H/2 * * * *') 
   }
  stages {
  
    stage('Test and build') {
      steps {
          echo "testing ..."
	      sh 'mvn --settings pipeline/settings.xml clean package'
      }
    }
    
    stage('Deploiment CloudHub to Sandbox') {
      when {
          branch 'dev'
      } 
      environment {
          ENVIRONMENT= "Sandbox"
      }
      steps {
          sh "mvn -e -X deploy -Dmule.env=${ENVIRONMENT.toLowerCase()} -DmuleDeploy -Dmule.version=${MULE_VERSION} -Danypoint.username=${DEPLOY_CREDS_USR} -Danypoint.password=${DEPLOY_CREDS_PSW} -Dcloudhub.app=${APP_NAME}-${ENVIRONMENT.toLowerCase()} -Dcloudhub.environment=${ENVIRONMENT} -Dcloudhub.bg=${BG} -Dcloudhub.bgid=${BGID}  -Dcloudhub.worker=${WORKERS} -Dcloudhub.workersize=${WORKERSIZE} -Dcloudhub.region=${REGION}"
      }
    }
    
    stage('Deploiment CloudHub to Develop') { 
      when {
          branch 'main'
      }
      environment {
          ENVIRONMENT= "Develop"
      }
      steps {
          sh "mvn -e -X deploy -Dmule.env=${ENVIRONMENT.toLowerCase()} -DmuleDeploy -Dmule.version=${MULE_VERSION} -Danypoint.username=${DEPLOY_CREDS_USR} -Danypoint.password=${DEPLOY_CREDS_PSW} -Dcloudhub.app=${APP_NAME}-${ENVIRONMENT.toLowerCase()} -Dcloudhub.environment=${ENVIRONMENT} -Dcloudhub.bg=${BG} -Dcloudhub.bgid=${BGID}  -Dcloudhub.worker=${WORKERS} -Dcloudhub.workersize=${WORKERSIZE} -Dcloudhub.region=${REGION}"
      }
    }
    
    stage('slack-notification') {
            steps {
                slackSend(
                 color:  "good",
                 message: "<$JOB_URL|$JOB_NAME> ($currentBuild.currentResult): Build <$RUN_DISPLAY_URL|$BUILD_DISPLAY_NAME> ($currentBuild.durationString) : ",
                 baseUrl: "https://devops-ngp9932.slack.com/services/hooks/jenkins-ci",
                 channel: "général"
                 ) 
            }
        }
        stage('mail-notification') {
            steps {
                emailext(
                    subject: '$DEFAULT_SUBJECT', 
                    to: 'ibtissammdarbi@gmail.com', 
                    body: 'OK'
                )
            }
        }
  }
}

							