pipeline {
  agent any
  environment {
     DEPLOY_CREDS_USR = credentials('deploy-anypoint-user')
     cloudhub.username=""
     cloudhub.password=""
     cloudhub.applicationName="customer-api"
     cloudhub.environment=
     cloudhub.businessGroup="Cap4"
     cloudhub.businessGroupId="6a860bc2-7c16-4fc4-8c42-9a362133e5f9"
     cloudhub.region="us-east-2"
     cloudhub.workerType="Micro"
     cloudhub.workers="1"
     deploy.env=develop
     deploy.client_id="5a690a46de9044c58299752d21e85a14"
     deploy.client_secret="aFc62e8F0cd8496d9E3E0223cbC397dc"
     deploy.api-gatekeeper="disabled"
     deploy.api-monitoring="true"
	     
	  
  } 
  triggers {
        pollSCM('H/2 * * * *') 
   }
  stages {
  
    stage('Test and build') {
      steps {
          echo "testing ..."
	      sh 'mvn -e -X clean package --settings pipeline/settings.xml -Pcloudhub-deploy-env'
      }
    }
    
    stage('Deploiment CloudHub to Sandbox') {
      when {
          branch 'dev'
      } 
      environment {
          deploy.env== "Sandbox"
      }
      steps {
          sh "mvn -e -X deploy -DmuleDeploy --settings pipeline/settings.xml -Pcloudhub-deploy-env -Danypoint.username=${DEPLOY_CREDS_USR} -Danypoint.password=${DEPLOY_CREDS_PSW}"
      }
    }
    
    stage('Deploiment CloudHub to Develop') { 
      when {
          branch 'main'
      }
      environment {
          deploy.env== "Develop"
      }
      steps {
          sh "mvn -e -X deploy -DmuleDeploy --settings pipeline/settings.xml -Pcloudhub-deploy-env -Danypoint.username=${DEPLOY_CREDS_USR} -Danypoint.password=${DEPLOY_CREDS_PSW}"
      }
    }
    
    stage('slack-notification') {
            steps {
                slackSend(
                 color:  "good",
                 message: "<$JOB_URL|$JOB_NAME> ($currentBuild.currentResult): Build <$RUN_DISPLAY_URL|$BUILD_DISPLAY_NAME> ($currentBuild.durationString) : ",
                 baseUrl: "https://devops-ngp9932.slack.com/services/hooks/jenkins-ci",
                 channel: "général"
                 ) 
            }
        }
        stage('mail-notification') {
            steps {
                emailext(
                    subject: '$DEFAULT_SUBJECT', 
                    to: 'ibtissammdarbi@gmail.com', 
                    body: 'OK'
                )
            }
        }
  }
}

							