#%RAML 1.0
title: customer-api

/customer:
  get:
    description:  recuperation des donnes clients
    responses:
      200:
        body:
          application/json:
            example: |
              [ 
               {"accountID": "AC123","name": "The first account"}, 
               {"accountID": "AC456","name": "The second account"} 
              ] 
              
          
        
